In [1]:
import numpy as np 
import pandas as pd
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.preprocessing import StandardScaler, Normalizer

## MLP Classifier using Diabetes Dataset

In [2]:
dbt = pd.read_csv("diabetes.csv")
dbt.head()

,pregnencies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
dbt.isna().sum()

pregnencies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [4]:
X = dbt.drop("outcome", axis=1)
Y = dbt["outcome"]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [7]:
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.fit_transform(X_test)
mlpclassifier = MLPClassifier(hidden_layer_sizes=(120), activation='relu', solver='adam', random_state=1, verbose=True)
mlpclassifier.fit(X_train_std, Y_train)

Iteration 1, loss = 0.69960017
Iteration 2, loss = 0.66805294
Iteration 3, loss = 0.64108380
Iteration 4, loss = 0.61798304
Iteration 5, loss = 0.59926141
Iteration 6, loss = 0.58304939
Iteration 7, loss = 0.57000865
Iteration 8, loss = 0.55911128
Iteration 9, loss = 0.54877880
Iteration 10, loss = 0.54009470
Iteration 11, loss = 0.53261359
Iteration 12, loss = 0.52608915
Iteration 13, loss = 0.52032570
Iteration 14, loss = 0.51500548
Iteration 15, loss = 0.50965405
Iteration 16, loss = 0.50508167
Iteration 17, loss = 0.50175358
Iteration 18, loss = 0.49861808
Iteration 19, loss = 0.49544914
Iteration 20, loss = 0.49285164
Iteration 21, loss = 0.49018325
Iteration 22, loss = 0.48732744
Iteration 23, loss = 0.48502513
Iteration 24, loss = 0.48285386
Iteration 25, loss = 0.48095868
Iteration 26, loss = 0.47902829
Iteration 27, loss = 0.47751911
Iteration 28, loss = 0.47596209
Iteration 29, loss = 0.47446704
Iteration 30, loss = 0.47314408
Iteration 31, loss = 0.47151235
Iteration 32, loss = 0.46959072
Iteration 33, loss = 0.46845975
Iteration 34, loss = 0.46731407
Iteration 35, loss = 0.46622420
Iteration 36, loss = 0.46507058
Iteration 37, loss = 0.46364824
Iteration 38, loss = 0.46236133
Iteration 39, loss = 0.46126513
Iteration 40, loss = 0.46035508
Iteration 41, loss = 0.45954741
Iteration 42, loss = 0.45878435
Iteration 43, loss = 0.45817941
Iteration 44, loss = 0.45748416
Iteration 45, loss = 0.45689241
Iteration 46, loss = 0.45648963
Iteration 47, loss = 0.45589613
Iteration 48, loss = 0.45544078
Iteration 49, loss = 0.45493930
Iteration 50, loss = 0.45440626
Iteration 51, loss = 0.45361263
Iteration 52, loss = 0.45322984
Iteration 53, loss = 0.45235446
Iteration 54, loss = 0.45229104
Iteration 55, loss = 0.45203522
Iteration 56, loss = 0.45121879
Iteration 57, loss = 0.45077640
Iteration 58, loss = 0.45017624
Iteration 59, loss = 0.44967109
Iteration 60, loss = 0.44923412
Iteration 61, loss = 0.44859865
Iteration 62, loss = 0.44806907
Iteration 63, loss = 0.44770403
Iteration 64, loss = 0.44735355
Iteration 65, loss = 0.44679921
Iteration 66, loss = 0.44625327
Iteration 67, loss = 0.44587583
Iteration 68, loss = 0.44544529
Iteration 69, loss = 0.44481694
Iteration 70, loss = 0.44448819
Iteration 71, loss = 0.44365209
Iteration 72, loss = 0.44342010
Iteration 73, loss = 0.44311722
Iteration 74, loss = 0.44224775
Iteration 75, loss = 0.44191143
Iteration 76, loss = 0.44172485
Iteration 77, loss = 0.44179067
Iteration 78, loss = 0.44127056
Iteration 79, loss = 0.44093884
Iteration 80, loss = 0.44065391
Iteration 81, loss = 0.44035646
Iteration 82, loss = 0.44010472
Iteration 83, loss = 0.43970199
Iteration 84, loss = 0.43949347
Iteration 85, loss = 0.43899266
Iteration 86, loss = 0.43861850
Iteration 87, loss = 0.43850066
Iteration 88, loss = 0.43801878
Iteration 89, loss = 0.43751190
Iteration 90, loss = 0.43719010
Iteration 91, loss = 0.43713451
Iteration 92, loss = 0.43690514
Iteration 93, loss = 0.43629606
Iteration 94, loss = 0.43565188
Iteration 95, loss = 0.43517318
Iteration 96, loss = 0.43509893
Iteration 97, loss = 0.43500132
Iteration 98, loss = 0.43506964
Iteration 99, loss = 0.43454003
Iteration 100, loss = 0.43408990
Iteration 101, loss = 0.43337296
Iteration 102, loss = 0.43300154
Iteration 103, loss = 0.43261926
Iteration 104, loss = 0.43255730
Iteration 105, loss = 0.43258137
Iteration 106, loss = 0.43220742
Iteration 107, loss = 0.43169436
Iteration 108, loss = 0.43144239
Iteration 109, loss = 0.43100022
Iteration 110, loss = 0.43095556
Iteration 111, loss = 0.43065074
Iteration 112, loss = 0.43045380
Iteration 113, loss = 0.43029468
Iteration 114, loss = 0.43008816
Iteration 115, loss = 0.43004912
Iteration 116, loss = 0.43063674
Iteration 117, loss = 0.43095522
Iteration 118, loss = 0.43134072
Iteration 119, loss = 0.43130178
Iteration 120, loss = 0.43127101
Iteration 121, loss = 0.43099142
Iteration 122, loss = 0.43070518
Iteration 123, loss = 0.42990993
Iteration 124, loss = 0.42859922
Iteration 125, loss = 0.42792922
Iteration 126, loss = 0.42792634
Iteration 127, loss = 0.42760272
Iteration 128, loss = 0.42707558
Iteration 129, loss = 0.42698425
Iteration 130, loss = 0.42632025
Iteration 131, loss = 0.42629654
Iteration 132, loss = 0.42629228
Iteration 133, loss = 0.42643908
Iteration 134, loss = 0.42622613
Iteration 135, loss = 0.42644561
Iteration 136, loss = 0.42634207
Iteration 137, loss = 0.42599975
Iteration 138, loss = 0.42549654
Iteration 139, loss = 0.42492049
Iteration 140, loss = 0.42430227
Iteration 141, loss = 0.42388380
Iteration 142, loss = 0.42335200
Iteration 143, loss = 0.42305591
Iteration 144, loss = 0.42276704
Iteration 145, loss = 0.42207021
Iteration 146, loss = 0.42130113
Iteration 147, loss = 0.42106086
Iteration 148, loss = 0.42148473
Iteration 149, loss = 0.42143064
Iteration 150, loss = 0.42116283
Iteration 151, loss = 0.42122176
Iteration 152, loss = 0.42083059
Iteration 153, loss = 0.42067838
Iteration 154, loss = 0.42034111
Iteration 155, loss = 0.42018263
Iteration 156, loss = 0.41983975
Iteration 157, loss = 0.41928963
Iteration 158, loss = 0.41923793
Iteration 159, loss = 0.41917840
Iteration 160, loss = 0.41926641
Iteration 161, loss = 0.41895121
Iteration 162, loss = 0.41870809
Iteration 163, loss = 0.41803268
Iteration 164, loss = 0.41753053
Iteration 165, loss = 0.41754519
Iteration 166, loss = 0.41723882
Iteration 167, loss = 0.41712445
Iteration 168, loss = 0.41705446
Iteration 169, loss = 0.41706691
Iteration 170, loss = 0.41682061
Iteration 171, loss = 0.41653657
Iteration 172, loss = 0.41636864
Iteration 173, loss = 0.41575336
Iteration 174, loss = 0.41545265
Iteration 175, loss = 0.41538091
Iteration 176, loss = 0.41506617
Iteration 177, loss = 0.41475356
Iteration 178, loss = 0.41444212
Iteration 179, loss = 0.41414248
Iteration 180, loss = 0.41410954
Iteration 181, loss = 0.41361207
Iteration 182, loss = 0.41308316
Iteration 183, loss = 0.41273004
Iteration 184, loss = 0.41246767
Iteration 185, loss = 0.41217225
Iteration 186, loss = 0.41193976
Iteration 187, loss = 0.41175871
Iteration 188, loss = 0.41172722
Iteration 189, loss = 0.41149007
Iteration 190, loss = 0.41170159
Iteration 191, loss = 0.41188105
Iteration 192, loss = 0.41203817
Iteration 193, loss = 0.41177044
Iteration 194, loss = 0.41173053
Iteration 195, loss = 0.41117120
Iteration 196, loss = 0.41043915
Iteration 197, loss = 0.41001737
Iteration 198, loss = 0.40975930
Iteration 199, loss = 0.40916284
Iteration 200, loss = 0.40889843

c:\users\abhis\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=120, random_state=1, verbose=True)

In [8]:
print("Training Score:", mlpclassifier.score(X_train_std, Y_train)*100)
print("Testing Score:", mlpclassifier.score(X_test_std, Y_test)*100)

Training Score: 80.78175895765473
Testing Score: 81.16883116883116

## MLP Regressor using Housing Dataset

In [9]:
housing = pd.read_csv("housing.csv")
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [10]:
housing.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [11]:
housing.total_bedrooms.fillna(housing["total_bedrooms"].mean(), inplace=True)
housing.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [12]:
housing.drop("ocean_proximity", axis=1, inplace=True)
x = housing.drop("median_house_value", axis=1)
y = housing["median_house_value"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
mlpregressor = MLPRegressor(hidden_layer_sizes=(200, 140), activation='relu')
mlpregressor.fit(x_train, y_train)
print("Training Score:", mlpregressor.score(x_train, y_train)*100)
print("Testing Score:", mlpregressor.score(x_test, y_test)*100)

c:\users\abhis\appdata\local\programs\python\python39\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Training Score: 67.2468344302719
Testing Score: 65.26178027655303